version: '3'

services:
  management-mysql:
    image: 'mysql:8'
    container_name: assignments-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: assignments
    volumes:
      - .:/docker-entrypoint-initdb.d
